services:
  # The Database Service
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=phoebudget
    ports:
      - "5432:5432" # Expose port locally so you can still inspect with a GUI tool
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./migrations:/docker-entrypoint-initdb.d # DISABLE THIS: The API now handles migrations!

      # Your Rust App Service
  api:
    build: .
    restart: on-failure
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=phoebudget
      - JWT_SECRET=MY_SECRETTT
      - RUST_LOG=debug

volumes:
  postgres_data:
